apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}
type: Opaque
data:
    apikey: {{ .Values.apikey | b64enc | quote }}
    # the value will be from the command line with the --set flag. Putting it in values.yaml is insecure.