version: "3.9"
services:
  auth:
    restart: always
    build: ./auth
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PASSWORD: my-secret-pw
    networks:
    # we can no longer use the default docker bridge local network 172. app-net is a docker network that allows
    # all the containers to talk to each other via flat bridge.
      - app-net
  ui:
    restart: always
    build: ./UI
    depends_on:
    # UI is dependent on both the auth and weather containers being up and running
      - auth
      - weather
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
    ports:
    # these ports need to be exposed to client outside world
      - "3000:3000"
    networks:
      - app-net
  weather:
    restart: always
    build: ./weather
    environment:
      #APIKEY: ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
      APIKEY: 6eafbb0c45msh451df8302c291f2p1e0a35jsnf98732edea29
    networks:
      - app-net
  db:
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - app-net
    volumes:
      - ./db-data:/var/lib/mysql

networks:
  app-net:
    driver: bridge
volumes:
  db-data: